<a href="https://colab.research.google.com/github/JeeYz/fly_me_to_the_moon/blob/master/mnist_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.11.0


In [6]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [7]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [8]:
predictions = model(x_train[:1]).numpy()
predictions

array([[0.09588572, 0.09915303, 0.11571947, 0.03275376, 0.16092937,
        0.07548532, 0.11438493, 0.04182597, 0.09401479, 0.16984761]],
      dtype=float32)

In [9]:
tf.nn.softmax(predictions).numpy()

array([[0.0995017 , 0.09982733, 0.1014949 , 0.09341414, 0.10618877,
        0.0974924 , 0.10135953, 0.09426548, 0.09931572, 0.10714003]],
      dtype=float32)

In [10]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [11]:
loss_fn(y_train[:1], predictions).numpy()

2.327981

In [12]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [14]:
model.fit(x_train, y_train, epochs=10)

model.evaluate(x_test,  y_test, verbose=2)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0655 - accuracy: 0.9794
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0579 - accuracy: 0.9818
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0520 - accuracy: 0.9838
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0479 - accuracy: 0.9839
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0444 - accuracy: 0.9854
313/313 - 1s - loss: 0.0701 - accuracy: 0.9809 - 750ms/epoch - 2ms/step


[0.07012590020895004, 0.98089998960495]

In [15]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [16]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.08533675, 0.08533675, 0.08533675, 0.08533679, 0.08533675,
        0.08533675, 0.08533675, 0.23196916, 0.08533675, 0.08533677],
       [0.08533709, 0.08533939, 0.23196393, 0.08533709, 0.08533709,
        0.08533709, 0.08533709, 0.08533709, 0.08533709, 0.08533709],
       [0.08533915, 0.2319312 , 0.0853395 , 0.08533918, 0.08533928,
        0.08533917, 0.08533917, 0.08535364, 0.08534057, 0.08533915],
       [0.23196647, 0.08533692, 0.08533759, 0.08533692, 0.08533692,
        0.08533724, 0.08533694, 0.08533692, 0.08533692, 0.08533712],
       [0.08536761, 0.08536761, 0.08536765, 0.08536761, 0.2314803 ,
        0.08536761, 0.08536761, 0.08536786, 0.08536761, 0.08557858]],
      dtype=float32)>